spring:
  datasource:
    url: jdbc:postgresql://prod-db-host:5432/pms_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

logging:
  level:
    root: WARN
    com.elva.pms: INFO

file:
  upload:
    directory: /var/pms/uploads 